%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/baoning/Dropbox/2DDynamicCycle/GRL_Draft/FitEvolution_DK94/DK94_Fig8DataDigitized_Friction.csv
%
% Auto-generated by MATLAB on 12-Mar-2023 14:01:27

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["D_DK94Friction", "f_DK94Friction"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DK94Fig8DataDigitizedFriction = readtable("/Users/baoning/Dropbox/2DDynamicCycle/GRL_Draft/FitEvolution_DK94/DK94_Fig8DataDigitized_Friction.csv", opts);


%% Clear temporary variables
clear opts