%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/baoning/Dropbox/2DDynamicCycle/GRL_Draft/FitEvolution_DK94/DK94_Fig8DataDigitized_Friction.csv
%
% Auto-generated by MATLAB on 12-Mar-2023 14:01:27

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["D_DGeo243bPA", "PA_DGeo243bPA"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DGeo243bPA = readtable("/Users/baoning/Dropbox/2DDynamicCycle/GRL_Draft/FitEvolution_DK94/DieterichGeo243b_TD_ContactAreaPerc.csv", opts);


%% Clear temporary variables
clear opts